version: 2

sources:
  - name: fam_pp
    schema: dvh_fam_pp
    tables:
      - name: fam_pp_meta_data
        description: 'inneholder meta_data for PP, OMP, PPN'
      - name: fam_pp_fagsak
        description: 'inneholder vedtaks informasjon'
      - name: fam_pp_diagnose
        description: 'inneholder diagnose informasjon'
      - name: fam_pp_perioder
        description: 'Inneholder infromasjon om perioder'
      - name: fam_pp_periode_utbet_grader
        description: 'Inneholder infromasjon om utbetalinger'

  - name: dt_p
    schema: dt_p
    tables:
      - name: dim_diagnose

  - name: dt_kodeverk
    description: 'Datavarehus dimensjons data'
    schema: dt_kodeverk
    tables:
      - name: dim_tid
        description: 'Inneholder infromasjon om tid'

  - name: person
    schema: dt_person
    tables:
      - name: ident_off_id_til_fk_person1




